// examples/angular/thai-address-autocomplete.component.ts
/**
 * Angular Standalone Component for thai-address-autocomplete.
 *
 * A self-contained component that wraps the headless autocomplete engine.
 * Use this when you prefer a component-based approach over the directive.
 *
 * Usage:
 * ```html
 * <thai-address-autocomplete
 *   [source]="provinceSource"
 *   [renderItem]="customRenderItem"
 *   [debounceMs]="150"
 *   [maxResults]="10"
 *   placeholder="พิมพ์ชื่อจังหวัด..."
 *   (addressSelect)="onSelect($event)"
 * />
 * ```
 *
 * To use this component:
 * 1. Install: npm install thai-address-autocomplete thai-address-universal
 * 2. Copy this file into your Angular project
 * 3. Import the component in your standalone component or NgModule
 */

import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core';

// In production, import from 'thai-address-autocomplete'
import { initAutocomplete } from '../../src/core';
import type {
  AutocompleteInstance,
  ClassNames,
  RenderContainerFn,
  RenderItemFn,
  SourceFn,
  ThaiAddressSuggestion,
} from '../../src/types';

@Component({
  selector: 'thai-address-autocomplete',
  standalone: true,
  template: `
    <input
      #inputEl
      type="text"
      [placeholder]="placeholder"
      [attr.aria-label]="ariaLabel"
      [class]="inputClass"
    />
  `,
})
export class ThaiAddressAutocompleteComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** Data source function (use adapter factories). */
  @Input({ required: true }) source!: SourceFn;

  /** Custom item renderer. */
  @Input() renderItem?: RenderItemFn;

  /** Custom container renderer. */
  @Input() renderContainer?: RenderContainerFn;

  /** CSS class name overrides. */
  @Input() classNames?: ClassNames;

  /** Input placeholder text. */
  @Input() placeholder = 'Search Thai address...';

  /** Input aria-label for accessibility. */
  @Input() ariaLabel = 'Search Thai address';

  /** Debounce delay in ms. @default 200 */
  @Input() debounceMs = 200;

  /** Minimum query length to trigger search. @default 1 */
  @Input() minLength = 1;

  /** Max number of suggestions. @default 20 */
  @Input() maxResults = 20;

  /** Additional CSS class for the input element. */
  @Input() inputClass = '';

  /** Emitted when a suggestion is selected. */
  @Output() addressSelect = new EventEmitter<ThaiAddressSuggestion>();

  @ViewChild('inputEl', { static: true })
  private inputRef!: ElementRef<HTMLInputElement>;

  private instance: AutocompleteInstance | null = null;

  ngAfterViewInit(): void {
    this.createInstance();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.instance) return;

    const relevantKeys: (keyof this)[] = [
      'source',
      'renderItem',
      'renderContainer',
      'classNames',
      'debounceMs',
      'minLength',
      'maxResults',
    ];

    const hasRelevantChange = relevantKeys.some((key) => key in changes);
    if (hasRelevantChange) {
      this.instance.updateOptions({
        source: this.source,
        renderItem: this.renderItem,
        renderContainer: this.renderContainer,
        classNames: this.classNames,
        debounceMs: this.debounceMs,
        minLength: this.minLength,
        maxResults: this.maxResults,
      });
    }
  }

  ngOnDestroy(): void {
    this.instance?.destroy();
    this.instance = null;
  }

  /** Provides access to the underlying autocomplete instance. */
  getInstance(): AutocompleteInstance | null {
    return this.instance;
  }

  private createInstance(): void {
    this.instance = initAutocomplete(this.inputRef.nativeElement, {
      source: this.source,
      onSelect: (item) => this.addressSelect.emit(item),
      renderItem: this.renderItem,
      renderContainer: this.renderContainer,
      classNames: this.classNames,
      debounceMs: this.debounceMs,
      minLength: this.minLength,
      maxResults: this.maxResults,
    });
  }
}

// examples/react/ThaiAddressAutocomplete.tsx
/**
 * React integration example for thai-address-autocomplete.
 *
 * This component wraps the headless autocomplete engine in a React component
 * that accepts render callbacks for full customization.
 *
 * Usage:
 * ```tsx
 * import { ThaiAddressAutocomplete } from './ThaiAddressAutocomplete';
 * import { createProvinceSource } from 'thai-address-autocomplete';
 *
 * function App() {
 *   return (
 *     <ThaiAddressAutocomplete
 *       source={createProvinceSource({ maxResults: 10 })}
 *       onSelect={(item) => console.log('Selected:', item)}
 *       placeholder="Search province..."
 *     />
 *   );
 * }
 * ```
 */

import React, { useEffect, useRef, useCallback } from 'react';

// Import types — in production, import from 'thai-address-autocomplete'
import type {
  ThaiAddressSuggestion,
  SourceFn,
  RenderItemFn,
  RenderContainerFn,
  ClassNames,
  AutocompleteInstance,
} from '../../src/types';

// Import core — in production, import from 'thai-address-autocomplete'
import { initAutocomplete } from '../../src/core';

/**
 * Props for the React ThaiAddressAutocomplete component.
 */
interface ThaiAddressAutocompleteProps {
  /** Data source function (use adapter factories). */
  source: SourceFn;
  /** Callback when a suggestion is selected. */
  onSelect: (item: ThaiAddressSuggestion) => void;
  /** Custom item renderer. */
  renderItem?: RenderItemFn;
  /** Custom container renderer. */
  renderContainer?: RenderContainerFn;
  /** CSS class name overrides. */
  classNames?: ClassNames;
  /** Input placeholder text. */
  placeholder?: string;
  /** Input aria-label for accessibility. */
  ariaLabel?: string;
  /** Debounce delay in ms. @default 200 */
  debounceMs?: number;
  /** Minimum query length to trigger search. @default 1 */
  minLength?: number;
  /** Max number of suggestions. @default 20 */
  maxResults?: number;
  /** Additional className for the input element. */
  className?: string;
}

/**
 * A React component that wraps the headless thai-address-autocomplete engine.
 *
 * Manages the lifecycle of the autocomplete instance via useEffect,
 * creating it on mount and destroying it on unmount.
 */
export const ThaiAddressAutocomplete: React.FC<ThaiAddressAutocompleteProps> = ({
  source,
  onSelect,
  renderItem,
  renderContainer,
  classNames,
  placeholder = 'Search Thai address...',
  ariaLabel = 'Search Thai address',
  debounceMs = 200,
  minLength = 1,
  maxResults = 20,
  className,
}) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const instanceRef = useRef<AutocompleteInstance | null>(null);

  // Stable callback refs to avoid re-initializing on every render
  const onSelectRef = useRef(onSelect);
  onSelectRef.current = onSelect;

  const stableOnSelect = useCallback((item: ThaiAddressSuggestion) => {
    onSelectRef.current(item);
  }, []);

  useEffect(() => {
    const inputEl = inputRef.current;
    if (!inputEl) return;

    const ac = initAutocomplete(inputEl, {
      source,
      onSelect: stableOnSelect,
      renderItem,
      renderContainer,
      classNames,
      debounceMs,
      minLength,
      maxResults,
    });

    instanceRef.current = ac;

    return () => {
      ac.destroy();
      instanceRef.current = null;
    };
  }, [source, stableOnSelect, renderItem, renderContainer, classNames, debounceMs, minLength, maxResults]);

  return (
    <input
      ref={inputRef}
      type="text"
      placeholder={placeholder}
      aria-label={ariaLabel}
      className={className}
    />
  );
};

export default ThaiAddressAutocomplete;
